my_db/contact/urls.py
# -*- coding: utf-8 -*-
"""
Created on Sat May 30 10:17:22 2020

@author: user
"""
from django.urls import path
from . import views

app_name='contact'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact_form/', views.contact_form, name='contact_form'),
    path('contact_form/contact/complete/', views.complete, name='complete'),    
]

my_db/my_db/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
import db_serv.views as db_serv

urlpatterns = [
    path('success/url/',db_serv.success),
    path('db_serv/',include('db_serv.urls')),
    path('admin/', admin.site.urls),
    path('',include('db_serv.urls')),
    path('contact/',include('contact.urls')),
]

my_db/contact/models.py
from django.db import models

# Create your models here.

my_db/contact/forms.py
# -*- coding: utf-8 -*-
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(label='件名', max_length=100)
    sender = forms.EmailField(label='Email', help_text='※ご確認の上、正しく入力してください。')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)
    myself = forms.BooleanField(label='同じ内容を受け取る', required=False)

my_db/contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail

""" 一覧画面"""
def index(request):
    return render(request, 'contact/index.html')
""" お問い合わせフォーム画面"""
def contact_form(request):
    return render(request, 'contact/contact_form.html')
""" 送信完了画面"""
def complete(request):
    return render(request, 'contact/complete.html')

def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            """ 追記"""
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            myself = form.cleaned_data['myself']
            recipients = [settings.EMAIL_HOST_USER]
            if myself:
                recipients.append(sender)
            try:
                send_mail(subject, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('無効なヘッダーが見つかりました。')
            return redirect('contact:complete')
    else:
        form = ContactForm()
    return render(request, 'contact/contact_form.html', {'form': form})

my_db/templates/contact/complete.html
<center>
<h1>送信完了</h1>
<a href="{% url 'contact:index' %}">
<p>トップへ</p>
</a>
</center>

my_db/templates/contact/contact_form.html
<style>

/* fieldブロックの上部20px空ける*/
.field  {
    margin-top: 20px;
}
/* ブロック要素にする*/
label {
    display: block;
}
/* 件名・Emailの枠*/
input {
    width: 20%;
    padding: 5px;
    box-sizing: border-box;
    border: solid 2px;
}
/* 注意書きを赤色指定*/
.help {
    color: red;
}
/* メッセージの枠*/
textarea {
    width: 50%;
    box-sizing: border-box;
    border-radius: 4px;
    border: solid 2px;
}
/* 送信ボタン*/
button {
    margin-top: 30px;
    width: 10%;
    padding: 5px;
}
</style>

<center>
<h1>入力フォーム</h1><hr><br>

<form action="{% url 'contact:contact_form' %}" method="post">
    {% csrf_token %}
<!-- for文使って要素を取り出す-->
{% for field in form %}
    <div class="field">
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
<button type="submit">送信</button>
</form>
</center>

my_db/templates/contact/index.html
<!doctype html>
<html>
  <head>
    <title>Webサイト</title>
  </head>
  <body>

<center>
<a href="{% url 'contact:contact_form' %}">
<h2>お問い合わせフォーム</h2>
</a>
</center>
</body>
</html>